package mohu.smartID.gitex.constants;

public class JSONResponses {
    public static final String RESPONSE_ROLE_DATA = "{\"roleData\":[{\"Role\":\"Piligrim\",\"Modules\":{\"M1\":{\"enabled\":true,\"features\":[\"F1\",\"F2\"]},\"M2\":{\"enabled\":true,\"features\":[\"F4\",\"F5\"]},\"M3\":{\"enabled\":true,\"features\":[\"F1\",\"F5\"]}}},{\"Role\":\"Tour_Guide\",\"Modules\":{\"M1\":{\"enabled\":true,\"features\":[\"F1\",\"F2\"]},\"M2\":{\"enabled\":true,\"features\":[\"F4\",\"F5\"]},\"M3\":{\"enabled\":true,\"features\":[\"F1\",\"F5\"]}}}]}";
    public static final String RESPONSE_PROFILE = "{\"imageUrl\":\"https://dummyimage.com/300/09f/fff.png\",\"name\":\"Roopesh\",\"phoneNumber\":\"9705791119\"}";
    public static final String RESPONSE_PILIGRIMS = "{\"piligrims\":[{\"imageUrl\":\"https://dummyimage.com/300/05f/fff.png\",\"name\":\"Jhon\",\"phoneNumber\":\"970579892\",\"distance\":\"2 kms away\"},{\"imageUrl\":\"https://dummyimage.com/300/19f/fff.png\",\"name\":\"Mathews\",\"phoneNumber\":\"9705591119\",\"distance\":\"5 kms away\"},{\"imageUrl\":\"https://dummyimage.com/300/59f/fff.png\",\"name\":\"Akbar\",\"phoneNumber\":\"9705791319\",\"distance\":\"12 kms away\"},{\"imageUrl\":\"https://dummyimage.com/300/99f/fff.png\",\"name\":\"Sam\",\"phoneNumber\":\"9605791119\",\"distance\":\"21 kms away\"}]}";
    public static final String RESPONSE_CHATMESSAGE = "{\"chatMessageList\":[{\"imageUrl\":\"https://dummyimage.com/300/05f/fff.png\",\"name\":\"Mamie Harvey\",\"chatMessage\":\"Hi there, how are you?\",\"time\":\"11:30 AM \"},{\"imageUrl\":\"https://dummyimage.com/300/19f/fff.png\",\"name\":\"Rhoda Olson\",\"chatMessage\":\"Ok, lets take the next route\",\"time\":\"5 AM\"},{\"imageUrl\":\"https://dummyimage.com/300/59f/fff.png\",\"name\":\"Akbar\",\"chatMessage\":\"i can't find the place\",\"time\":\"12:10 PM\"},{\"imageUrl\":\"https://dummyimage.com/300/99f/fff.png\",\"name\":\"Sam\",\"chatMessage\":\"I am good\",\"time\":\"2 PM \"}]}";
    public static final String RESPONSE_ORGANIZEERS = "{\"organizeers\":[{\"imageUrl\":\"https://dummyimage.com/300/05f/fff.png\",\"name\":\"Mamie Harvey\",\"organizeersType\":\"Tour Guide\",\"distance\":\"2 km away \"},{\"imageUrl\":\"https://dummyimage.com/300/05f/fff.png\",\"name\":\"Mamie Harvey\",\"organizeersType\":\"Tour Guide\",\"distance\":\"2 km away \"},{\"imageUrl\":\"https://dummyimage.com/300/05f/fff.png\",\"name\":\"Mamie Harvey\",\"organizeersType\":\"Tour Guide\",\"distance\":\"2 km away \"},{\"imageUrl\":\"https://dummyimage.com/300/05f/fff.png\",\"name\":\"Mamie Harvey\",\"organizeersType\":\"Tour Guide\",\"distance\":\"2 km away \"},{\"imageUrl\":\"https://dummyimage.com/300/05f/fff.png\",\"name\":\"Mamie Harvey\",\"organizeersType\":\"Tour Guide\",\"distance\":\"2 km away \"},{\"imageUrl\":\"https://dummyimage.com/300/05f/fff.png\",\"name\":\"Mamie Harvey\",\"organizeersType\":\"Tour Guide\",\"distance\":\"2 km away \"},{\"imageUrl\":\"https://dummyimage.com/300/05f/fff.png\",\"name\":\"Mamie Harvey\",\"organizeersType\":\"Tour Guide\",\"distance\":\"2 km away \"},{\"imageUrl\":\"https://dummyimage.com/300/05f/fff.png\",\"name\":\"Mamie Harvey\",\"organizeersType\":\"Tour Guide\",\"distance\":\"2 km away \"},{\"imageUrl\":\"https://dummyimage.com/300/19f/fff.png\",\"name\":\"Dependra Bradhan\",\"organizeersType\":\"Murshid\",\"distance\":\"22 km away\"},{\"imageUrl\":\"https://dummyimage.com/300/59f/fff.png\",\"name\":\"Akbar\",\"organizeersType\":\"Mutawwif\",\"distance\":\"2 km away\"},{\"imageUrl\":\"https://dummyimage.com/300/99f/fff.png\",\"name\":\"Sam\",\"organizeersType\":\"Tour Guide\",\"distance\":\"12 km away\"}]}";
/*    public static final String RESPONSE_ORGANIZEERS = "{\"organizeers\":[{\"imageUrl\":\"https://dummyimage.com/300/05f/fff.png\",\"name\":\"Mamie Harvey\",\"organizeersType\":\"Tour Guide\",\"distance\":\"2 km away \"},{\"imageUrl\":\"https://dummyimage.com/300/19f/fff.png\",\"name\":\"Dependra Bradhan\",\"organizeersType\":\"Murshid\",\"distance\":\"22 km away\"},{\"imageUrl\":\"https://dummyimage.com/300/59f/fff.png\",\"name\":\"Akbar\",\"organizeersType\":\"Mutawwif\",\"distance\":\"2 km away\"},{\"imageUrl\":\"https://dummyimage.com/300/99f/fff.png\",\"name\":\"Sam\",\"organizeersType\":\"Tour Guide\",\"distance\":\"12 km away\"}]}";*/
    public static final String RESPONSE_CONTACTS = "{\"contacts\":[{\"imageUrl\":\"https://dummyimage.com/300/05f/fff.png\",\"name\":\"Mamie Harvey\",\"distance\":\"2 km away \"},{\"imageUrl\":\"https://dummyimage.com/300/19f/fff.png\",\"name\":\"Dependra Bradhan\",\"distance\":\"22 km away\"},{\"imageUrl\":\"https://dummyimage.com/300/59f/fff.png\",\"name\":\"Akbar\",\"distance\":\"2 km away\"},{\"imageUrl\":\"https://dummyimage.com/300/99f/fff.png\",\"name\":\"Sam\",\"distance\":\"12 km away\"}]}";
    public static final String RESPONSE_RESTAURANATS = "{\"restaurants\":[{\"imageUrl\":\"https://dummyimage.com/300/05f/fff.png\",\"name\":\"Radisson Blu Hotel \",\"rating\":\"3.9 \",\"distance\":\"2 km away \"},{\"imageUrl\":\"https://dummyimage.com/300/05f/fff.png\",\"name\":\"Buraj AI Balad\",\"rating\":\"2.5 \",\"distance\":\"2 km away \"},{\"imageUrl\":\"https://dummyimage.com/300/05f/fff.png\",\"name\":\"Red sea Palace\",\"rating\":\"5 \",\"distance\":\"2 km away \"},{\"imageUrl\":\"https://dummyimage.com/300/05f/fff.png\",\"name\":\"Golden Hotel\",\"rating\":\"4.5 \",\"distance\":\"2 km away \"}]}";
    public static final String RESPONSE_INCIDENTS = "{\"IncidentList\":[{\"incidentMessage\":\"Hi, I lost my mobile \",\"incidentStatus\":\"seen \",\"time\":\"2 PM \"},{\"incidentMessage\":\"Hi, i lost my BAG \",\"incidentStatus\":\"seen \",\"time\":\"5 PM \"},{\"incidentMessage\":\"Hi, not able to find \",\"incidentStatus\":\"sent \",\"time\":\"4 PM \"}]}";
    public static final String RESPONSE_NOTIFICATION = "{\"notifications\":[{\"imageUrl\":\"https://dummyimage.com/300/05f/fff.png\",\"message\":\"Message from Alex Jones\",\"time\":\"2 min ago \"},{\"imageUrl\":\"https://dummyimage.com/300/05f/fff.png\",\"message\":\"Heavy traffic \",\"time\":\"7 min ago\"},{\"imageUrl\":\"https://dummyimage.com/300/05f/fff.png\",\"message\":\"Heavy rain\",\"time\":\"11 min ago\"},{\"imageUrl\":\"https://dummyimage.com/300/05f/fff.png\",\"message\":\"Message from Alex Jones\",\"time\":\"2 min\"}]}";
}
